import { css } from 'styled-system/css';

export const markdownStyles = css({
  lineHeight: '1.8',
  fontSize: { base: '1.5rem', tablet: '1.6rem' },
  wordBreak: 'keep-all',
  overflowWrap: 'break-word',

  '& h1': {
    fontSize: { base: '2.4rem', tablet: '2.8rem' },
    fontWeight: 'bold',
    marginTop: '8',
    marginBottom: '4',
    lineHeight: '1.3',
    letterSpacing: '-0.02em',
  },
  '& h2': {
    fontSize: { base: '1.9rem', tablet: '2.2rem' },
    fontWeight: 'bold',
    marginTop: '6',
    marginBottom: '3',
    lineHeight: '1.3',
    letterSpacing: '-0.015em',
    borderBottom: '1px solid',
    borderColor: 'border',
    paddingBottom: '2',
  },
  '& h3': {
    fontSize: { base: '1.6rem', tablet: '1.8rem' },
    fontWeight: 'semibold',
    marginTop: '5',
    marginBottom: '2',
    lineHeight: '1.4',
  },
  '& p': {
    marginBottom: '4',
  },
  '& a': {
    color: 'primary',
    textDecoration: 'underline',
    textUnderlineOffset: '0.2em',
    textDecorationThickness: '1px',
    _hover: { color: 'primary.dark' },
  },
  '& ul, & ol': {
    marginBottom: '4',
    paddingLeft: { base: '2.4rem', tablet: '3rem' },
  },
  '& li': {
    marginBottom: '2',
  },
  '& blockquote': {
    borderLeft: '3px solid',
    borderColor: 'secondary',
    paddingLeft: { base: '1.2rem', tablet: '1.6rem' },
    paddingBlock: '0.8rem',
    marginBottom: '4',
    marginInline: 0,
    color: 'textSecondary',
    backgroundColor: 'surfaceHover',
    borderRadius: '0 0.6rem 0.6rem 0',
    fontStyle: 'italic',
  },
  '& code': {
    background: 'codeBg',
    padding: '0.2rem 0.5rem',
    borderRadius: '0.4rem',
    fontSize: '0.88em',
    fontFamily: '{fonts.mono}',
    wordBreak: 'break-all',
  },
  '& pre': {
    background: 'codeBlockBg',
    color: 'white',
    padding: { base: '1.2rem', tablet: '1.6rem' },
    borderRadius: '0.8rem',
    overflow: 'auto',
    marginBottom: '4',
    fontSize: { base: '1.3rem', tablet: '1.4rem' },
    lineHeight: 1.6,
    WebkitOverflowScrolling: 'touch',

    '& code': {
      background: 'transparent',
      padding: '0',
      fontSize: 'inherit',
      wordBreak: 'normal',
    },
  },
  '& hr': {
    border: 'none',
    borderTop: '1px solid',
    borderColor: 'border',
    marginTop: '6',
    marginBottom: '6',
  },
  '& table': {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: '4',
    display: 'block',
    overflowX: 'auto',
    WebkitOverflowScrolling: 'touch',
  },
  '& th, & td': {
    border: '1px solid',
    borderColor: 'border',
    padding: { base: '0.6rem 0.8rem', tablet: '0.8rem 1.2rem' },
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  '& th': {
    background: 'surfaceHover',
    fontWeight: 'semibold',
  },
  '& img': {
    maxWidth: '100%',
    height: 'auto',
    borderRadius: '0.8rem',
    marginBottom: '4',
  },
});
