/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeIndexRouteImport } from './routes/resume/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesDetailArticleIdIndexRouteImport } from './routes/articles/detail/$articleId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeIndexRoute = ResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesDetailArticleIdIndexRoute =
  ArticlesDetailArticleIdIndexRouteImport.update({
    id: '/articles/detail/$articleId/',
    path: '/articles/detail/$articleId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/resume/': typeof ResumeIndexRoute
  '/articles/detail/$articleId/': typeof ArticlesDetailArticleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/contact': typeof ContactIndexRoute
  '/resume': typeof ResumeIndexRoute
  '/articles/detail/$articleId': typeof ArticlesDetailArticleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/resume/': typeof ResumeIndexRoute
  '/articles/detail/$articleId/': typeof ArticlesDetailArticleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/'
    | '/contact/'
    | '/resume/'
    | '/articles/detail/$articleId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articles' | '/contact' | '/resume' | '/articles/detail/$articleId'
  id:
    | '__root__'
    | '/'
    | '/articles/'
    | '/contact/'
    | '/resume/'
    | '/articles/detail/$articleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ResumeIndexRoute: typeof ResumeIndexRoute
  ArticlesDetailArticleIdIndexRoute: typeof ArticlesDetailArticleIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/': {
      id: '/resume/'
      path: '/resume'
      fullPath: '/resume/'
      preLoaderRoute: typeof ResumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/detail/$articleId/': {
      id: '/articles/detail/$articleId/'
      path: '/articles/detail/$articleId'
      fullPath: '/articles/detail/$articleId/'
      preLoaderRoute: typeof ArticlesDetailArticleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ResumeIndexRoute: ResumeIndexRoute,
  ArticlesDetailArticleIdIndexRoute: ArticlesDetailArticleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
